sources:
- fetcher: url
  name: subs
  options:
    urls:
    - https://fs.v2rayse.com/share/20250121/6kjliui7i9.yaml
    - http://mm.mibei77.com/202501/01.21Clashikl.yaml
    - https://raw.githubusercontent.com/changfengoss/pub/main/data/2025_01_21/6hemwb.yaml
    - https://raw.githubusercontent.com/changfengoss/pub/main/data/2025_01_21/BK2wyY.yaml
    - https://raw.githubusercontent.com/changfengoss/pub/main/data/2025_01_21/Ip9ZPc.yaml
    - https://raw.githubusercontent.com/changfengoss/pub/main/data/2025_01_21/YlZuAd.yaml
    - https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0121.txt
    - https://clashgithub.com/wp-content/uploads/rss/20250121.txt
    - https://nodefree.githubrowcontent.com/2025/01/20250121.yaml
    - https://v2rayshare.githubrowcontent.com/2025/01/20250121.yaml
    - https://oneclash.githubrowcontent.com/2025/01/20250121.yaml
    - https://wenode.githubrowcontent.com/2025/01/20250121.yaml
    - https://www.naidounode.com/node/20250121-clash.yaml
    - https://clash-meta.github.io/uploads/2025/01/0-20250121.txt
    - https://clash-meta.github.io/uploads/2025/01/1-20250121.txt
    - https://clash-meta.github.io/uploads/2025/01/2-20250121.txt
    - https://clash-meta.github.io/uploads/2025/01/3-20250121.txt
    - https://clash-meta.github.io/uploads/2025/01/4-20250121.txt
    - https://clashfree.github.io/uploads/2025/01/0-20250121.txt
    - https://clashfree.github.io/uploads/2025/01/1-20250121.txt
    - https://clashfree.github.io/uploads/2025/01/2-20250121.txt
    - https://clashfree.github.io/uploads/2025/01/3-20250121.txt
    - https://clashfree.github.io/uploads/2025/01/4-20250121.txt
  output: sub/sources/dynamicAll.yaml
