http-port: 23940 #port to run http proxy on
api-port: 23941 #api port
threads: 50 #线程数，指一次扫描多少个节点
source: ./sub/sources/fetchshareAll.yaml #你的输入文件名, 注意必须是YAML配置文件格式, 此处是input.yaml
outfile: ./sub/rx.yaml #你的输出文件名, 注意输出文件也是YAML配置文件格式, 此处是output.yaml
outfile_base64: ./sub/rx64  #输出的base64文件格式
test-url: http://www.gstatic.com/generate_204 #https://www.google.com/favicon.ico #延迟测试地址, 可以更改
#test-url: https://www.youtube.com/s/desktop/bcc5b1af/img/favicon.ico
#test-url: https://www.youtube.com/s/player/23010b46/player_ias.vflset/en_US/remote.js #延迟测试地址, 可以更改
timeout: 1000 #测试的超时界限, timeout in miliseconds
