http-port: 23940 #port to run http proxy on
api-port: 23941 #api port
threads: 50 #线程数，指一次扫描多少个节点
source: ./sub/sources/all.yaml #你的输入文件名, 注意必须是YAML配置文件格式, 此处是input.yaml
outfile: ./sub/sources/checked.yaml #你的输出文件名, 注意输出文件也是YAML配置文件格式, 此处是output.yaml
test-url: https://www.youtube.com/s/player/23010b46/player_ias.vflset/en_US/remote.js #延迟测试地址, 可以更改
timeout: 5000 #测试的超时界限, timeout in miliseconds
